First Draft of Grabble (ODF) top-lvl idea
tbsexton/grabble pull request #1
Opened 2022-09-28 22:36 UTC by tbsexton

2022-09-30 13:37 UTC, markfuge requested changes
@tbsexton 
For your "core ideas" section here I would, for the purposes of the paper, relabel or add a section entitled "contributions" which lays out. Not just existing ideas taken from other libraries, but rather than new knowledge that you had to generate in order to enable the key functionalities that you lay out here.

For example, you lay out in bullets here something about labeled incidence tensors. Is this something new that you are proposing or is this from an existing body of work that you are merely implementing in this case? If the latter, that may still be fine If there was some sort of key intellectual block that prevented others from leveraging that idea in this application; in which case, your contribution to knowledge would be how to overcome that blockage.

Ultimately, you will want your contributions list to be fleshed out with the following elements for each item in the bullet list:
1. Claim. What is the key claim to knowledge that you are making? That is what new thing did we not know before that your paper will now tell us? You can check the lab hand book for examples of these.
2. Evidence. What is a one or two sentence description of the evidence that your paper plans to put forth that you have achieved that claim? This helps a reviewer quickly match the claim to the provided evidence.
3. (Optional for now) Takeaway. Assuming that your claim is backed up by the evidence that you provide, why is this contribution to knowledge important? What does it allow us to do now that was not possible before or what new avenues to knowledge creation does it open? This allows a reviewer to quickly estimate the impact of the claim.

I suggest morphing this core ideas section into a new key contributions section and incorporating the suggestions above. I'll then be able to give you more concrete feedback on your planned evidence structure.

2022-11-18 06:32 UTC, tbsexton commented
@markfuge Ok I had some time to write context and motivation a bit more. 

I also added some "touchstone" papers that live in the space/tone/style/contribution-type that I am targeting, under "reading material". Especially that first one. 

So, e.g. I'm translating that muon paper into a set of claim/evidence/takeaway by highlighting what looks to me like something that accomplishes your asks there. Fundamentally I think it's difficult to talk about stuff like this in absolutes like "key claim to knowledge with evidence that it's new/better", for the same reason it would be hard to do that for a paper that digs into the nuances of, say, Composition vs. Inheritance. or e.g. the Rassmussen paper on Skills, Rules, & Knowledge.  But those papers are still classic references and needed tools. 

My go-to, then, is usually to have a sort of pros/cons vs other "ways of looking at things", with the outcome of _here are situations when doing things in the way I'm saying makes a lot of sense, and here's the logic/studies/evidence that backs those up_. Obviously I can hack in an objective thing or two like "yes, in fact running pagerank on a sparse network in my library is way faster than the implementation in pandas or networkx... for python, on this computer... on a rainy day...". But the really good meat here is hopefully in the _subjective_ stuff, since that's where all the juicy problems and hard thinking/study/cross-context stuff is happening

2022-11-18 19:03 UTC, markfuge reviewed
Adding comments based on high-level bullets that you provided. This needs to be fleshed out further and crystallized since it is still not super clear what you are proposing to contribute toward new knowledge. I noted places in the document where this clarification might bring this out.

2022-11-18 19:03 UTC, markfuge commented on docs/index.md
> +## What are needs of modern network analysis?
Sounds like this is kind of motivation/introduction? If so, for some of the things you mention below as problems, it would strengthen the paper to provide references to this. For example, other papers or sources that mention these needs.

2022-11-18 19:03 UTC, markfuge commented on docs/index.md
> +Often, the representations we choose to store and share our network data in carry implied constraints, or even features, that are not intended.
Provide examples here after this sentence to help the reader.

2022-11-18 19:03 UTC, markfuge commented on docs/index.md
> +Edgelists are the quintissential example of graph data structures:
To help with flow, consider: "For example, edgelists are the ...." form since that will tie this next paragraph directly to the needs you highlight above

2022-11-18 19:03 UTC, markfuge commented on docs/index.md
> +This kind of implied structure is very common, whether in the use of assumed-symmetric adjacency matrices for undirected graphs (and their Laplacians). Because the underlying intention for the graph
It would be helpful to highlight an actual concrete problem that arises because of this. You mention "analyst memory is required to ensure the data is being used or transformed correctly downstream." but this is too abstract. What is an example of a usage or transformation that could erroneously result if the analyst forgets this implicit graph structure? This will help ground the abstract example and help people see the motivation

2022-11-18 19:03 UTC, markfuge commented on docs/index.md
> +It is preferable to make the process of realizing a serialized data set one that naturally answers fundamental question about the nature of the structure being preserved.
This comment is a bit vague, to be honest. This could be clarified with a concrete example of how "making the process of realizing...data"  into "one that answers a question" about "a structure being preserved".

2022-11-18 19:03 UTC, markfuge commented on docs/index.md
> +> by making key features of the data structure's format more _explicit_ and _available_, a well-designed format will naturally assist users in selecting appropriate graph structures
How would I know or measure whether or not I have made a data structure's format "more explicit" and "available"

Also, how would I assess whether a format was "well designed" and whether a user "selected appropriate graph structures"?

2022-11-18 19:03 UTC, markfuge commented on docs/index.md
> +The reality is that almost all of these don't interop in many meaningful ways, outside of occaisional import/export[^4]. Some attempts to deal with this are working more as parsers (in python), e.g.
Can you define in more precise terms what you mean by "do not interop in many meaningful ways"? If so, this could actually help you crystallize and sharpen the contributions of any tools you might develop for this, as well as provide concrete success measures that you could use as evidence

2022-11-18 19:03 UTC, markfuge commented on docs/index.md
> +papers I would like to use as tone/template guides
Looking through these now. As your writing evolves on this we can refer back to them, but it is hard to assess their connection and impact in isolation/abstraction. Better to think of them in the context of words you actually write down yourself, then we will have a concrete example.

2022-12-09 14:28 UTC, tbsexton commented
@markfuge still have to clean up a notebook or two, but I've added all of the code from working out how exactly this "looks" in a way that's usable/sustainable/understandable. THat should help the writing process so we all can reference something while moving forward. 

I've included some `DEPRECATED` files/folders, for the time being. Those are all ways I've tried to implement the idea, but couldn't work out for one reason or another. Good references to describe why certain architectures wouldn't work in the proposal sections.

2022-12-09 14:46 UTC, merged

2022-12-09 15:19 UTC, markfuge commented
@tbsexton I tried looking through the notebooks but I didn't get a sense of what you actually wanted feedback on. Was there a specific thing you were looking for input on?